- `try catch finally`
    
    ```kotlin
    fun parseIntOrThrow(str: String): Int {
    	try {
    		return str.toInt()
    	} catch (e: NumberFormatException) {
    		throw IllegalArgumentException("주어진 ${str}는 숫자가 아닙니다")
    	}
    }
    
    fun parseIntOrThrowV2(str: String): Int? {
    	return try {
    		str.toInt()
    	} catch (e: NumberFormatException) {
    		null
    	}
    }
    ```
    
    - 타입이 뒤에 위치한다.
    - new를 사용하지 않는다.
    - 포맷팅이 간결하다.
- `Checked Exception과 Unchecked Exception`
    
    ```kotlin
    fun readFile() {
    	val currentFile = File(".")
    	val file = File(currentFile.absolutePath + "/a.txt")
    	val reader = BufferedReader(FileReader(file))
    	println(reader.readLine())
    	reader.close()
    }
    ```
    
    - IOException을 던지지 않아도 된다.
    - 코틀린에서는 `Checked Exception과 Unchecked Exception` 을 구분하지 않는다.
    - **모두 Unchecked Exception!!!!**
- `try with resources`
    
    ```kotlin
    fun readFile(path: String) {
    	BufferedReader(FileReader(path)).use { reader ->
    		println(reader.readLine())
    	}
    }
    ```
    
    - 코틀린에는 `try with resources` 구문이 없기 때문에 **use**를 사용해야함
